name: check pr maintainer perms
on:
  pull_request:
    types:
      - opened

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.maintainer_can_modify == false }}
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "It works!"
            })
